---
title: "Enflasyon ve Ekonomik Büyüme"
author: 
  - Ayca Bayrak[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080375, [Github Repo](https://github.com/aycabayrak/aycabayrak_arasinav.git)


# Giriş
Fiyat istikrarı ve ekonomik büyümenin gerçekleşmesi bir toplumun refah seviyesini belirlemede en önemli iki etkendir. Genel olarak iktisatta enflasyon, cari fiyat seviyesinde toplam talebin toplam arzdan fazla olmasıdır. Bunun sonucunda genel fiyat seviyesi yükselir ve toplam talep kısılarak toplam arza eşit bir duruma gelmiş olur. Enflasyonu fiyatlar genel seviyesinin yükselmesi olarak da adlandırırken dikkat etmemiz gereken husus fiyatlardaki her yükselişin enflasyon olmadığıdır. Önemli olan bu artışın sürekli ve büyük olmasıdır. Kısa sürede hızla yükselen fiyat seviyesinin bir süre sonra durulmasını enflasyon olarak tanımlayamayız.
Enflasyonu iki başlık altında inceleyebiliriz: 1)Kaynaklarına Göre Enflasyon, 2) Hızlarına Göre Enflasyon.Kaynaklarına göre enflasyon; talep enflasyonu, maliyet enflasyonu olarak ikiye ayrılabiliriz.Hızlarına göre enflasyonu; hiperenflasyon ve belirsiz enflasyon olarak ikiye ayırabiliriz.
Ekonomik büyüme, bir ekonomide üretim hacmindeki dönemsel artışlardır. Bu artışın en önemli belirleyicilerinden biri Gayri Safi Yurtiçi Hasıla'daki(GSYH) artıştır. Ekonomik büyüme, gelişmiş ülkelerin daha çok önem verdiği bir konudur. Gelişmekte olan ülkeler ise ekonomik kalkınma hususuna dikkat etmektedir. Ekonomik kalkınma, ekonomik büyümeyi içermekle birlikte işsizliğin azaltılması, gelir dengesizliğinin azaltılması gibi alanlara da önem vermektedir.

## Çalışmanın Amacı
Yaptığım araştırmada, enflasyon ile ekonomik büyümenin arasındaki ilişkiyi Türkiye ve OECD kurucu üyelerinden ABD, Birleşik Krallık, İsveç, Hollanda, Yunanistan, Almanya, Fransa, İtalya, İtalya ülkelerinin verilerini referans alarak araştırdım. Araştırmamda, OECD verilerinden yararlandım. Ülkelerin enflasyonu TÜFE verileri ile, ekonomik büyümeleri ise GSYH ile yorumlanmıştır. GSYH, kişi başına ABD doları ile; TÜFE ise yıllık büyüme oranı ile hesaplanmıştır. Veriler 2022 yılı baz alınarak hazırlanmıştır. 
Hala ortak bir görüşte karar kılınamamış olmakla birlikte birçok araştırma enflasyon ve ekonomik büyüme arasındaki bağı ele alır. 1980’lerin aksine son yıllarda, büyüme ve enflasyon arasında pozitif bir ilişki olduğu düşüncesi yaygınlaşmaya başlamıştır. İstikrarlı ekonomik büyüme, refah ve ekonomik kalkınma seviyenin arttırılması için önemlidir. Tam bu noktada enflasyon ve ekonomik büyüme arasındaki ilişkiyi incelemek mevcut ekonominin işleyişini kontrol etmekte oldukça fayda sağlar.

## Literatür 
Enflasyon ve ekonomik büyüme üzerine yapılan çalışmaların kökleri klasik iktisat teorilerinden modern teorilere kadar uzanmaktadır. Bugün ekonomik büyümeyi ilerletmede enflasyonun göreli önemi bir tartışma konusu olmaya devam ediyor. Merkez bankalarının çoğu para politikaları, düşük enflasyon oranı ve yüksek ekonomik büyüme sağlamayı amaçlar.
Son zamanlarda yapılan araştırmalarda enflasyonun ekonomik büyümeyi olumsuz yönde etkilediği iddia edilse de daha öneki çalışmalar enflasyonun ekonomik büyümeyi olumlu yönde etkilediğini öne sürüyor.Mevcut literatürde bu konu üçe ayrılabilir: enflasyonun ekonomik büyümeyi olumlu etkilediği, enflasyonun ekonomik büyümeyi olumsuz etkilediği, enflasyonun belli koşullarla ekonomik büyümeyi olumlu/olumsuz etkilediği. [@akinsola2017inflation]
Fakat yapılan araştırmaların geneline bakıldığında önemli olanın enflasyon oranından ziyade mevcut hükümetin aldığı önemler olduğu görülmektedir. Fiyat istikrarının sağlanması amacıyla hükümet çarpan etkisini göz ardı ederek toplam harcamaları azaltıcı politika uygularsa ekonomik büyümenin daha fazla azalmasına neden olabilir. Bu durumda pozitif ya da negatif bir etkiden bahsetmek için bazı değişkenlerin söz konusu olduğu söylenebilir. [@bahad2011enflasyon]
Yaptığım araştırmada verilere baktığımız zaman, Türkiye’nin diğer ülkelere oranla enflasyon seviyesinin çok yüksek olduğunu görmekteyiz. Fakat buna karşılık yine Türkiye’nin Gayri Safi Yurtiçi Hasılası diğer ülkelerden oldukça düşüktür. En düşük enflasyon oranı Fransa’da iken en yüksek Gayri Safi Yurtiçi Hasıla ise Hollanda’dır. 
Türkiye, 1970'lerde yüksek enflasyonun etkilerini yaşamış, 1980'lerde ise yetersiz yapısal uyumun olumsuz etkileriyle karşı karşıya kalmıştır. Ekonomi kısa vadeli sermaye girişleriyle desteklenmiş, büyümeyi teşvik eden uygulamalarda tüketim teşvik edilirken kamu sektörü finansman dengesi bozulmuştur. 1990'larda meydana gelen stagflasyon sırasında, enflasyonun ekonomik büyümenin maliyeti olduğu görüşü yoğunluk kazanmıştır. [@albayrak9ekonomik]
Ekonomik büyümenin diğer etkenlerinin sabit  tutulduğu bir araştırmada enflasyonun 10 puanlık artışından GSYH büyüme oranının %0,2-0,3 oranında azalarak etkilendiği görülmüştür. Bu da enflasyon oranının ekonomik büyüme üzerindeki etkisinin negatif olduğunu gösterir.[@gokal2004relationship]


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>

